[CONFIG]
# Config data should be entered with out quotes.

# Get your teams rapidViewId from the url of your Jira board. Example: /secure/RapidBoard.jspa?rapidView=**123**
RAPID_VIEW_ID =
# Get your JSESSIONID from your browsers cookies.
JSESSION_ID =
# Team name to be displayed in the title of the slides.
TEAM_NAME =
# Should stories in backlog be added to presentation (yes/no)
BACKLOG = no